name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Lint
        run: ruff check src tests
      - name: Format (check)
        run: black --check src tests
      - name: Test
        run: pytest -q
      - name: Build Docker image (smoke)
        run: docker build -t geo-seg:local .
      - name: Run container (smoke training)
        run: |
          mkdir -p _out
          docker run --rm -v "$PWD/_out:/out" geo-seg:local
          test -f _out/best.pt
