name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Lint
        run: ruff check src tests
      - name: Format (check)
        run: black --check src tests
      - name: Test
        run: pytest -q
      - name: Upload run artifacts (if present)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: runs-and-eval
          path: |
            runs/**/metrics.csv
            runs/**/eval.json
          if-no-files-found: ignore
